# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 726205d8c1dd54cc30f9ff5d895d7d00250a9a86d1ddb58dfdd92251e0c45d0c9b2856264b814ca8ff770c49ebc7a440927900b3c241259641d56f8c9cef7096

test:
  secret_key_base: e7c90a1851c9ee924ac61ddb32784cf869d5f458feddb10fed762fa5fc1033c60ce2685a932df74e6bd727b2d196c0cde1fd7088dac4cdaeb1c4419608f6eec6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
